modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"
issueTrackerURL = "https://github.com/Ocelot5836/ModelAnima/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "ModelAnima"
updateJSONURL="https://raw.githubusercontent.com/Ocelot5836/storage/master/mods/model-anima/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/model-anima"
#logoFile = "examplemod.png"
#credits = ""
authors = "Ocelot5836"
description = "A simple library that allows usage of Minecraft Bedrock Geometry models to animate entities easier."

[modproperties.${mod_id}]
#catalogueItemIcon="beyond:rocket_thruster"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"