modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"
issueTrackerURL = "https://github.com/Ocelot5836/ModelAnima/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "ModelAnima"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://github.com/Ocelot5836/ModelAnima"
#logoFile = "examplemod.png"
#credits = ""
authors = "Ocelot5836"
description = "A simple library that allows usage of Minecraft Bedrock Geometry models to animate entities easier."

[modproperties.beyond]
#catalogueItemIcon="beyond:rocket_thruster"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"